<a href="https://colab.research.google.com/github/itssajitha/Python-bootcamp-journey/blob/main/Day7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [5]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(a+b)
print(a*b)

[5 7 9]
[ 4 10 18]


In [6]:
c=np.array([10,20,30,40,50])

print(np.sum(c))
print(np.mean(c))
print(np.max(c))
print(np.min(c))


150
30.0
50
10


In [7]:
import pandas as pd


In [12]:
data ={"Name":["Ali","Sara","John","Emma"],
"Age":[20,22,21,19]
       }

df=pd.DataFrame(data)
df[df['Age'] > 20]

,Name,Age
1,Sara,22
2,John,21
